#!/bin/sh

mkdir /tmp/rpms

cd /tmp/rpms

koji download-build --arch=x86_64 kernel-5.13.9-200.fc34

wget https://www.thefanclub.co.za/sites/default/files/public/overgrive/overgrive-3.3.10.noarch.rpm
wget http://download.ebz.epson.net/dsc/op/stable/RPMS/x86_64/epson-inkjet-printer-201215w-1.0.0-1lsb3.2.x86_64.rpm
wget https://downloads.mongodb.com/compass/mongodb-compass-1.30.1.x86_64.rpm
wget https://dl4jz3rbrsfum.cloudfront.net/software/PPL-1.3.3-64bit.rpm
wget https://github.com/JonMagon/KDiskMark/releases/download/2.3.0/kdiskmark-2.3.0-1.x86_64.rpm
wget https://github.com/raro28/vfio-gpu-passthrough-scripts/releases/download/0.0.2/vfio-gpu-passthrough-scripts-0.0.2-1.fc35.x86_64.rpm
wget https://github.com/raro28/qemu-hook-scripts/releases/download/0.0.0/qemu-hook-scripts-0.0.0-3.fc35.x86_64.rpm
wget https://github.com/raro28/gdm-desktop-monitor-xml/releases/download/0.0.0/gdm-desktop-monitor-xml-0.0.0-1.fc35.x86_64.rpm
wget https://github.com/raro28/gdm-laptop-monitor-xml/releases/download/0.0.0/gdm-laptop-monitor-xml-0.0.0-1.fc35.x86_64.rpm
wget https://github.com/raro28/dconf-local-db-config/releases/download/0.0.0/dconf-local-db-config-0.0.0-1.fc35.x86_64.rpm
wget https://github.com/raro28/looking-glass-client/releases/download/B5.0.1/looking-glass-client-B5.0.1-1.fc35.x86_64.rpm

createrepo /tmp/rpms

busybox httpd -p 127.0.0.1:8000 -h /tmp/rpms