#!/bin/sh

mkdir /tmp/rpms

cd /tmp/rpms

koji download-build --arch=x86_64 kernel-5.13.9-200.fc34

wget https://www.thefanclub.co.za/sites/default/files/public/overgrive/overgrive-3.4.2.noarch.rpm
wget http://download.ebz.epson.net/dsc/op/stable/RPMS/x86_64/epson-inkjet-printer-201215w-1.0.0-1lsb3.2.x86_64.rpm
wget https://downloads.mongodb.com/compass/mongodb-compass-1.30.1.x86_64.rpm
wget https://downloads.mongodb.com/compass/mongodb-mongosh-1.2.2.el8.x86_64.rpm
wget https://dl4jz3rbrsfum.cloudfront.net/software/PPL-1.3.3-64bit.rpm
wget https://github.com/JonMagon/KDiskMark/releases/download/2.3.0/kdiskmark-2.3.0-1.x86_64.rpm
wget https://launchpad.net/veracrypt/trunk/1.25.9/+download/veracrypt-1.25.9-CentOS-8-x86_64.rpm

createrepo /tmp/rpms

busybox httpd -p 127.0.0.1:8000 -h /tmp/rpms